# Generated by Django 5.1.6 on 2025-02-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_rename_full_name_contact_fn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="favorite",
            field=models.BooleanField(default=False, verbose_name="Favorite"),
            preserve_default=False,
        ),
    ]
