# Generated by Django 5.1.6 on 2025-02-15 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contact_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="pub_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Non Editable, public id",
                null=True,
                verbose_name="Public ID",
            ),
        ),
    ]
