# Generated by Django 5.1.6 on 2025-02-15 08:57
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Contacts = apps.get_model("contacts", "Contact")
    for row in Contacts.objects.all():
        row.pub_id = uuid.uuid4()
        row.save(update_fields=["pub_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_add_uuid_field"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
