# Generated by Django 5.1.6 on 2025-02-15 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="pub_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                null=False,
            ),
        ),
    ]
