# Generated by Django 5.1.6 on 2025-02-28 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_add_unique_to_pub_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Not Required. Image here will be prioritized over avatar_url image. Image should be 1080x1080",
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pub_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Non Editable, public id",
                unique=True,
                verbose_name="Public ID",
            ),
        ),
    ]
